var searchData=
[
  ['patologia_2ecs_0',['Patologia.cs',['../_patologia_8cs.html',1,'']]],
  ['patologiaconfiguration_2ecs_1',['PatologiaConfiguration.cs',['../_patologia_configuration_8cs.html',1,'']]],
  ['patologiaproxy_2ecs_2',['PatologiaProxy.cs',['../_patologia_proxy_8cs.html',1,'']]],
  ['patologieservice_2ecs_3',['PatologieService.cs',['../_patologie_service_8cs.html',1,'']]],
  ['paziente_2ecs_4',['Paziente.cs',['../_paziente_8cs.html',1,'']]],
  ['pazienteconfiguration_2ecs_5',['PazienteConfiguration.cs',['../_paziente_configuration_8cs.html',1,'']]],
  ['pazienteproxy_2ecs_6',['PazienteProxy.cs',['../_paziente_proxy_8cs.html',1,'']]],
  ['pazientiservice_2ecs_7',['PazientiService.cs',['../_pazienti_service_8cs.html',1,'']]],
  ['permessoprofilo_2ecs_8',['PermessoProfilo.cs',['../_permesso_profilo_8cs.html',1,'']]],
  ['permessoprofiloconfiguration_2ecs_9',['PermessoProfiloConfiguration.cs',['../_permesso_profilo_configuration_8cs.html',1,'']]],
  ['permissions_2ecs_10',['Permissions.cs',['../_permissions_8cs.html',1,'']]],
  ['permissionsservice_2ecs_11',['PermissionsService.cs',['../_permissions_service_8cs.html',1,'']]],
  ['predizione_2ecs_12',['Predizione.cs',['../_predizione_8cs.html',1,'']]],
  ['predizioneconfiguration_2ecs_13',['PredizioneConfiguration.cs',['../_predizione_configuration_8cs.html',1,'']]],
  ['predizioneproxy_2ecs_14',['PredizioneProxy.cs',['../_predizione_proxy_8cs.html',1,'']]],
  ['profilo_2ecs_15',['Profilo.cs',['../_profilo_8cs.html',1,'']]],
  ['profiloconfiguration_2ecs_16',['ProfiloConfiguration.cs',['../_profilo_configuration_8cs.html',1,'']]]
];
