var searchData=
[
  ['accounts_0',['Accounts',['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_accounts.html',1,'Molim::Backend::API::DTO']]],
  ['algoritmi_1',['Algoritmi',['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_algoritmi.html',1,'Molim::Backend::API::DTO']]],
  ['api_2',['API',['../namespace_molim_1_1_backend_1_1_a_p_i.html',1,'Molim::Backend']]],
  ['auth_3',['Auth',['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_auth.html',1,'Molim::Backend::API::DTO']]],
  ['backend_4',['Backend',['../namespace_molim_1_1_backend.html',1,'Molim']]],
  ['diagnosi_5',['Diagnosi',['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_pazienti_1_1_diagnosi.html',1,'Molim::Backend::API::DTO::Pazienti']]],
  ['dto_6',['DTO',['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o.html',1,'Molim::Backend::API']]],
  ['errors_7',['Errors',['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_errors.html',1,'Molim::Backend::API::DTO']]],
  ['esami_8',['Esami',['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_pazienti_1_1_esami.html',1,'Molim::Backend::API::DTO::Pazienti']]],
  ['molim_9',['Molim',['../namespace_molim.html',1,'']]],
  ['molim_2ebackend_2eapi_2edto_2eassemblyinfo_2ecs_10',['Molim.Backend.API.DTO.AssemblyInfo.cs',['../_molim_8_backend_8_a_p_i_8_d_t_o_8_assembly_info_8cs.html',1,'']]],
  ['patologie_11',['Patologie',['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_patologie.html',1,'Molim::Backend::API::DTO']]],
  ['pazienti_12',['Pazienti',['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_pazienti.html',1,'Molim::Backend::API::DTO']]],
  ['predizioni_13',['Predizioni',['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_pazienti_1_1_predizioni.html',1,'Molim::Backend::API::DTO::Pazienti']]],
  ['requests_14',['Requests',['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_accounts_1_1_requests.html',1,'Molim.Backend.API.DTO.Accounts.Requests'],['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_auth_1_1_requests.html',1,'Molim.Backend.API.DTO.Auth.Requests'],['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_pazienti_1_1_diagnosi_1_1_requests.html',1,'Molim.Backend.API.DTO.Pazienti.Diagnosi.Requests'],['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_pazienti_1_1_predizioni_1_1_requests.html',1,'Molim.Backend.API.DTO.Pazienti.Predizioni.Requests'],['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_pazienti_1_1_requests.html',1,'Molim.Backend.API.DTO.Pazienti.Requests']]],
  ['responses_15',['Responses',['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_accounts_1_1_responses.html',1,'Molim.Backend.API.DTO.Accounts.Responses'],['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_algoritmi_1_1_responses.html',1,'Molim.Backend.API.DTO.Algoritmi.Responses'],['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_auth_1_1_responses.html',1,'Molim.Backend.API.DTO.Auth.Responses'],['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_patologie_1_1_responses.html',1,'Molim.Backend.API.DTO.Patologie.Responses'],['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_pazienti_1_1_diagnosi_1_1_responses.html',1,'Molim.Backend.API.DTO.Pazienti.Diagnosi.Responses'],['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_pazienti_1_1_esami_1_1_responses.html',1,'Molim.Backend.API.DTO.Pazienti.Esami.Responses'],['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_pazienti_1_1_predizioni_1_1_responses.html',1,'Molim.Backend.API.DTO.Pazienti.Predizioni.Responses'],['../namespace_molim_1_1_backend_1_1_a_p_i_1_1_d_t_o_1_1_pazienti_1_1_responses.html',1,'Molim.Backend.API.DTO.Pazienti.Responses']]]
];
